<?php
error_reporting(E_ALL);
ini_set('display_errors', TRUE);
define('KANJIUM_DATABASE', './kanjium/data/kanjidb.sqlite');
define('SITE_TITLE', 'Kanjislide');
define('JLPT_LEVELS', [
  1 => 'N1 (advanced)',
  2 => 'N2 (intermediate)',
  3 => 'N3 (lower intermediate)',
  4 => 'N4 (basic)',
  5 => 'N5 (beginner)',
]);

define('CONJUGATIONS_ADJI', [
	'plain_polite' => 'plain polite',
	'plain_neg' => 'plain neg',
	'plain_neg_polite' => 'plain_neg_polite',
	'past' => 'past',
	'past_polite' => 'past_polite',
	'past_neg' => 'past_neg',
	'past_neg_polite' => 'past_neg_polite',
	'te_form' => 'te_form',
	'te_form_neg' => 'te_form_neg',
	'conditional' => 'conditional',
	'conditional_neg' => 'conditional_neg',
	'provisional' => 'provisional',
	'provisional_neg' => 'provisional_neg',
	'adverbial' => 'adverbial',
	'nominalization' => 'nominalization',
]);


define('CONJUGATIONS_VERB', [
	'plain_polite' => 'plain_polite',
	'plain_neg' => 'plain_neg',
	'plain_neg_polite' => 'plain_neg_polite',
	'nu_form' => 'nu_form',
	'mu_form' => 'mu_form',
	'past' => 'past',
	'past_polite' => 'past_polite',
	'past_neg' => 'past_neg',
	'past_neg_polite' => 'past_neg_polite',
	'te_form' => 'te_form',
	'te_form_polite' => 'te_form_polite',
	'te_form_neg' => 'te_form_neg',
	'te_form_neg_polite' => 'te_form_neg_polite',
	'zu_form' => 'zu_form',
	'conditional' => 'conditional',
	'conditional_polite' => 'conditional_polite',
	'conditional_neg' => 'conditional_neg',
	'conditional_neg_polite' => 'conditional_neg_polite',
	'provisional' => 'provisional',
	'provisional_polite' => 'provisional_polite',
	'provisional_neg' => 'provisional_neg',
	'provisional_neg_polite' => 'provisional_neg_polite',
	'volitional' => 'volitional',
	'volitional_polite' => 'volitional_polite',
	'volitional_neg' => 'volitional_neg',
	'volitional_neg_polite' => 'volitional_neg_polite',
	'imperative' => 'imperative',
	'imperative_polite' => 'imperative_polite',
	'imperative_neg' => 'imperative_neg',
	'imperative_neg_polite' => 'imperative_neg_polite',
	'potential' => 'potential',
	'potential_polite' => 'potential_polite',
	'potential_neg' => 'potential_neg',
	'potential_neg_polite' => 'potential_neg_polite',
	'potential_past' => 'potential_past',
	'potential_past_polite' => 'potential_past_polite',
	'potential_neg_past' => 'potential_neg_past',
	'potential_neg_past_polite' => 'potential_neg_past_polite',
	'passive' => 'passive',
	'passive_polite' => 'passive_polite',
	'passive_neg' => 'passive_neg',
	'passive_neg_polite' => 'passive_neg_polite',
	'passive_past' => 'passive_neg_polite',
	'passive_past_polite' => 'passive_past_polite',
	'passive_neg_past' => 'passive_neg_past',
	'passive_neg_past_polite' => 'passive_neg_past_polite',
	'causative' => 'causative',
	'causative_polite' => 'causative_polite',
	'causative_neg' => 'causative_neg',
	'causative_neg_polite' => 'causative_neg_polite',
	'causative_past' => 'causative_past',
	'causative_past_polite' => 'causative_past_polite',
	'causative_neg_past' => 'causative_neg_past',
	'causative_neg_past_polite' => 'causative_neg_past_polite',
	'caus_passive' => 'caus_passive',
	'caus_passive_polite' => 'caus_passive_polite',
	'caus_passive_neg' => 'caus_passive_neg',
	'caus_passive_neg_polite' => 'caus_passive_neg_polite',
	'caus_passive_past' => 'caus_passive_past',
	'caus_passive_past_polite' => 'caus_passive_past_polite',
	'caus_passive_neg_past' => 'caus_passive_neg_past',
	'caus_passive_neg_past_polite' => 'caus_passive_neg_past_polite',
	'adverbial' => 'adverbial',
	'nominalization' => 'nominalization',
]);

